import logging
from dataclasses import dataclass
from time import perf_counter

import numpy as np
import tensorflow as tf
from numpy.typing import NDArray

from app.core import ModelManager

logger = logging.getLogger(__name__)


@dataclass(frozen=True, slots=True)
class InferenceResult:
    """Result of the model inference stage.

    Attributes:
        probabilities:
            Model output probabilities for each frame and note.

        piano_roll:
            Binary piano activation matrix generated from probabilities.

        threshold:
            Probability threshold used to generate the binary output.

        inference_time:
            Total inference duration in seconds.
    """

    probabilities: NDArray[np.float32]
    piano_roll: NDArray[np.bool_]
    threshold: float
    inference_time: float


class InferenceService:
    """Run inference using the trained TensorFlow model.

    The service reproduces the inference pipeline used during model
    validation:

        1. Feature normalization.
        2. TensorFlow model prediction.
        3. Probability extraction.
        4. Threshold application.
        5. Binary piano roll generation.
    """

    def __init__(
        self,
        model_manager: ModelManager,
    ) -> None:
        """Initialize the inference service.

        Args:
            model_manager:
                Manager providing the trained model and preprocessing objects.
        """

        self._manager: ModelManager = model_manager

    @property
    def model(self) -> tf.keras.Model:
        """Return the TensorFlow inference model."""

        return self._manager.model

    @property
    def threshold(self) -> float:
        """Return the probability threshold used for classification."""

        return self._manager.metadata.threshold

    def infer(
        self,
        features: NDArray[np.float32],
    ) -> InferenceResult:
        """Run inference on extracted audio features.

        Args:
            features:
                Feature tensor generated by the preprocessing pipeline.

        Returns:
            Inference result containing probabilities and binary activations.

        Raises:
            Exception:
                If feature normalization or model prediction fails.
        """

        logger.info("Running model inference.")

        logger.debug(
            "Inference input shape=%s.",
            features.shape,
        )

        start_time = perf_counter()

        try:
            logger.debug("Normalizing inference features.")

            scaled_features = self._manager.normalize_features(
                features,
            )

            logger.debug(
                "Normalized feature shape=%s.",
                scaled_features.shape,
            )

            logger.debug("Running TensorFlow model prediction.")

            probabilities = self.model.predict(
                scaled_features,
                verbose=0,
            ).astype(np.float32, copy=False)

        except Exception:
            logger.exception("Model inference failed.")
            raise

        inference_time = perf_counter() - start_time

        threshold = self.threshold

        piano_roll = probabilities >= threshold

        logger.info(
            "Inference completed in %.3f s.",
            inference_time,
        )

        logger.debug(
            (
                "Inference output: probabilities_shape=%s, "
                "piano_roll_shape=%s, threshold=%.3f."
            ),
            probabilities.shape,
            piano_roll.shape,
            threshold,
        )

        return InferenceResult(
            probabilities=probabilities,
            piano_roll=piano_roll,
            threshold=threshold,
            inference_time=inference_time,
        )
