name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          enable-cache: true

      - name: Install Python
        run: |
          uv python install 3.13
          uv python pin 3.13

      - name: Sync dependencies
        run: uv sync --group api

      - name: Run tests
        run: uv run pytest api/tests -v --disable-warnings