name: cicd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.13"
  COVERAGE_THRESHOLD: 1

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          enable-cache: true

      - name: Install Python
        run: |
          uv python install $PYTHON_VERSION
          uv python pin $PYTHON_VERSION

      - name: Sync dependencies
        run: uv sync --group api --group dev

      - name: Run tests
          uv run pytest \
            -v \
            --disable-warnings \
            --cov-fail-under=${{ env.COVERAGE_THRESHOLD }}

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-html
          path: htmlcov/

      - name: Upload XML coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-xml
          path: coverage.xml

  quality:
    name: Ruff & MyPy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          enable-cache: true

      - name: Install Python
        run: |
          uv python install $PYTHON_VERSION
          uv python pin $PYTHON_VERSION

      - name: Sync dependencies
        run: uv sync --group api --group dev

      - name: Run Ruff
        run: uv run ruff check api/backend api/frontend

      - name: Run MyPy
        run: uv run mypy api/backend api/frontend